# Generated by Django 6.0.3 on 2026-04-29 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authoкs',
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='CoverType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Cover type',
                'verbose_name_plural': 'Cover types',
                'db_table': 'cover_types',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='BookCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255)),
                ('pages_count', models.PositiveIntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='book_cards/')),
                ('status', models.CharField(choices=[('available', 'Доступна'), ('unavailable', 'Недоступна')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_cards', to='ads.author')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_cards', to=settings.AUTH_USER_MODEL)),
                ('cover_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_cards', to='ads.covertype')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_cards', to='ads.genre')),
            ],
            options={
                'verbose_name': 'Book card',
                'verbose_name_plural': 'Book cards',
                'db_table': 'book_cards',
                'ordering': ['-created_at'],
            },
        ),
    ]
