# Generated by Django 6.0.3 on 2026-04-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcard',
            name='status',
        ),
        migrations.AddField(
            model_name='bookcard',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
