# Generated by Django 6.0.3 on 2026-04-29 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_city_alter_author_options_bookcard_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcard',
            name='city',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.PROTECT, related_name='book_cards', to='ads.city'),
            preserve_default=False,
        ),
    ]
