# Generated by Django 6.0.3 on 2026-04-29 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0004_alter_bookcard_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_type', models.CharField(choices=[('bookcrossing', 'Точка буккросинга'), ('delivery', 'Доставка')], max_length=30)),
                ('bookcrossing_address', models.CharField(blank=True, max_length=500, null=True)),
                ('delivery_address', models.CharField(blank=True, max_length=500, null=True)),
                ('delivery_method', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='ads.bookcard')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_exchanges', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_exchanges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exchange',
                'verbose_name_plural': 'Exchanges',
                'db_table': 'exchanges',
                'ordering': ['-created_at'],
            },
        ),
    ]
